# -*- coding: utf-8 -*-
"""Colab-WebUI.ipynb のコピー

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRaUIS023GgYv6caCcenxzd4YULsQuQp

# GPT-SoVITS WebUI

## Env Setup (Run Once Only)
## 环境配置, 只需运行一次

### 1.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/setup.sh
# set -e
# 
# cd /content
# 
# git clone https://github.com/RVC-Boss/GPT-SoVITS.git
# 
# cd GPT-SoVITS
# 
# if conda env list | awk '{print $1}' | grep -Fxq "GPTSoVITS"; then
#     :
# else
#     conda create -n GPTSoVITS python=3.10 -y
# fi
# 
# source activate GPTSoVITS
# 
# pip install ipykernel
# 
# bash install.sh --device CU126 --source HF --download-uvr5

"""### 2."""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q condacolab
import condacolab
condacolab.install_from_url("https://repo.anaconda.com/archive/Anaconda3-2024.10-1-Linux-x86_64.sh")
!cd /content && bash setup.sh

"""## Launch WebUI
## 启动 WebUI
"""

# NOTE: must install into the GPTSoVITS conda env (python3.10), not the
# base Colab kernel (python3.12) -- webui.py runs inside that env, and a
# pip install outside it has no effect on the running server's imports.
# Root cause: gradio's routes.py calls the old-style
# templates.TemplateResponse(name, context) positional signature, which
# newer Starlette (>=0.46) no longer supports, causing
# "TypeError: unhashable type: 'dict'" on every page load.
# https://github.com/RVC-Boss/GPT-SoVITS/issues/2762
!source activate GPTSoVITS && pip install "starlette>=0.40.0,<0.46.0"

!cd /content/GPT-SoVITS && source activate GPTSoVITS && export is_share=True && python webui.py

from google.colab import drive
drive.mount('/content/drive')

import zipfile, glob, os
DATA = '/content/dataset'
SRC = '/content/drive/MyDrive/99_未分類/gpt_sovits_data_20260703'
os.makedirs(DATA, exist_ok=True)
for z in glob.glob(f'{SRC}/*.zip'):
    zipfile.ZipFile(z).extractall(DATA)

# train.list の相対パスを絶対パスへ書き換え
for lst in glob.glob(f'{DATA}/*/train.list'):
    root = os.path.dirname(lst)
    rows = open(lst, encoding='utf-8').read().splitlines()
    rows = [f'{root}/' + r if r.startswith('wavs/') else r for r in rows]
    open(lst.replace('train.list', 'train_abs.list'), 'w', encoding='utf-8').write('\n'.join(rows) + '\n')
print('done:', glob.glob(f'{DATA}/*/train_abs.list'))